---
- hosts: tomcat
  #become: yes
  tasks:
  - name: deploy war file to tomcat
    copy: 
      src: target/CounterWebApp.war 
      dest: /usr/share/tomcat/webapps
      owner: root
      group: root
      mode: '0644'

