---
- hosts: tomcat
  #become: yes
  tasks:
  - name: deploy war file to tomcat
    copy: 
      src: /var/lib/jenkins/workspace/Deploy2tomcat/target/CounterWebApp.war
      dest: /usr/share/tomcat/webapps


